export const COMPONENT_GALLERY_COMPONENTS = Object.freeze([
  'StatBar',
  'IconPicker',
  'DetailSection',
  'ContentRow',
  'OptionList',
  'SearchMultiSelect',
  'FloatingTooltip',

  'GuidedTour',
  'LoadingIndicator',
  'LoadingState',
  'SkeletonBlock',
  'BaseTile',
  'TileAccentStrip',
  'MorphTile',
  'MorphTileHeader',
  'SectionList',
  'AddButton',
  'ActionButton',
  'AppSlider',
  'CompactCheckbox',
  'MultiToggle',
  'RemoveButton',
  'SectionLabel',
  'TimelineGroup',
  'SegmentDonutChart',
  'SlidingTabs',
  'ToggleSwitch',
  'ActionMenu',
  'ActionMenuItem',
  'ActionMenuSubmenu',
  'BasePopover',
  'ColorPresetPicker',
  'ValueSelect',
  'RichContent',
  'RichTextEditor',
  'AccountMenu',
  'AppShell',
  'AppSidebar',
  'SidebarBrand',
  'SidebarGroup',
  'SidebarNavItem',
  'SidebarToggle',
  'EditorPanel',
  'EditorSection',
  'EditorSectionTitle',
  'EditorTotal',
  'AppModal',
  'AppModalFrame',
  'ConfirmDialog',
  'ModalShell',
  'MorphSheet',
  'TextPromptDialog',
  'FormActionButtons',
  'DatePicker',
  'FormField',
  'FormNumberInput',
  'FormSelect',
  'FormTextarea',
  'FormTextInput',
  'InlineEdit',
])

// Aliases are compatibility names for components already represented by their canonical export.
export const COMPONENT_GALLERY_ALIASES = Object.freeze({
  PromptDialog: 'TextPromptDialog',
  RowActionItem: 'ActionMenuItem',
  RowActionMenu: 'ActionMenu',
  RowActionSubmenu: 'ActionMenuSubmenu',
})
